h3js/srvx

playground/app.mjs

The emoji in the example HTML response may not render correctly in the playground's iframe (or when running the code locally) without a charset declared in the HTML or in the `Content-Type` header.

chore(playground): set charset in content-type header

---

docs/1.guide/0.why.md
docs/1.guide/2.handler.md

No connected issue, since this is a docs-only minor fix the casing of terms like `JavaScript`. 🙂

docs: minor tweaks 

---

src/node-utils/response.ts

The NodeFastResponse class is missing the `bytes()` method of the Response interface. [Link to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Response/bytes)

feat(node): add `NodeFastResponse.bytes()`

---

docs/1.guide/1.index.md
docs/1.guide/7.node.md

Some ref links were using `()`

doc: fix links

---

src/node-utils/send.ts

This PR improves the streamBody functions performance and closes the stream after it's completed.
This change is strongly inspired by [@honojs/node-server](https://github.com/honojs/node-server) approach.
Before:
```
Node.js:         v22.13.0
OS:              darwin arm64
OHA:             1.6.0
node... 116485 req/sec
srvx... 62466 req/sec
srvx-fast... 101216 req/sec
┌───────────┬──────────────────┐
│ (index)   │ Values           │
├───────────┼──────────────────┤
│ node      │ '116485 req/sec' │
│ srvx-fast │ '101216 req/sec' │
│ srvx      │ '62466 req/sec'  │
└───────────┴──────────────────┘
```
After:
```
Node.js:         v22.13.0
OS:              darwin arm64
OHA:             1.6.0
node... 115214 req/sec
srvx... 66832 req/sec
srvx-fast... 101813 req/sec
┌───────────┬──────────────────┐ …
```

refactor(node): improve body streaming

---

.gitignore
docs/1.guide/5.options.md
package.json
playground/app.mjs
src/_utils.ts
src/adapters/bun.ts
src/adapters/deno.ts
src/adapters/node.ts
src/types.ts

feat: support `tls` and `protocol`

---

src/_node-compat/send.ts
test/_fixture.ts
test/_tests.ts

discovered from https://github.com/nitrojs/nitro/pull/3208/
Node.js has a [slow path](http://github.com/nodejs/node/blob/v22.14.0/lib/_http_server.js#L377) for `res.writeHead` that only triggers if `res.setHeader` is called before.
In this case only (seems an implementation inconsistency) flatten array of key/value touples is expected.

fix(node): flatten headers to handle node slow path

---

test/node-fast.test.ts

Since `NodeFastResponse` was renamed to `NodeResponse` in 0cdfa22b37a805040cca809bf37cedb1505067d5, this PR updates the relevant import in `node-fast.test.ts`

chore: update node tests

---

docs/1.guide/2.handler.md
src/_node-compat/headers.ts
src/_node-compat/request.ts
src/_node-compat/url.ts
src/adapters/bun.ts
src/adapters/cloudflare.ts
src/adapters/deno.ts
src/types.ts
test/_fixture.ts
test/_tests.ts

Attaching `request.{key}` props makes runtime-specific addons harder to distinguish and extend from the rest of the standard request props.
This PR is an API breaking change that moved them under `x` key (`request.x?.ip`, `request.x?.runtime`, `request.x?.node`, ..)
Types now can be also easily extended from `ServerRuntimeContext`.
Node.js polyfills now use `_node` for internal node context (still available via `request.runtime` too)

refactor!: move extended request context under `request.x.*`

---

docs/1.guide/2.handler.md
src/_node-compat/request.ts
src/adapters/bun.ts
src/adapters/cloudflare.ts
src/adapters/deno.ts
src/types.ts
test/_fixture.ts

quick turnover from #50
Using more clearer `request.ip` and `request.runtime` namespaces.
(votes from [nitro discord](https://discord.nitro.build))

refactor!: use `request.ip` and `request.runtime`

---

package.json
playground/sw/index.html
playground/sw/sw.mjs
src/adapters/service-worker.ts
src/types.ts

This PR adds an experimental service-worker adapter to fill support for `browser` export condition.
Features:
- `serve` registers service worker and makes sure to reload and claim other clients
- skips for 404 responses and URLs with extension to be on safe side (might add option later)

feat: experimental service-worker adapter

---

package.json
src/adapters/generic.ts
src/types.ts

In case using `srvx` with default condition or only needing srvx for API compatibility (for example bypass in tests), generic adapter exposes server with `.fetch` method without any listener.

feat: generic adapter

---

docs/1.guide/4.plugins.md
src/_error.ts
src/_plugin.ts
src/adapters/bun.ts
src/adapters/cloudflare.ts
src/adapters/deno.ts
src/adapters/generic.ts
src/adapters/node.ts
src/adapters/service-worker.ts
src/types.ts
test/_fixture.ts
test/_tests.ts
test/node-fast.test.ts

Plugins with split `onRequest`/`onResponse` hooks can be a little faster due to linear executation and single wrapper but are also limited since there could not be corelation between request and response interception. For example we cannot implement a plugin for async context support.
This PR changes plugin format to simple `{ fetch(request, next) }` middleware system.
Note: found an issue with node-fast response headers interception support. Fixing in next PRs.

feat!: fetch middleware via plugins

---

src/_node-compat/request.ts
src/_node-compat/send.ts
src/_ws.ts
src/adapters/bun.ts
src/adapters/cloudflare.ts
src/adapters/deno.ts
src/adapters/node.ts
src/types.ts

This PR is initial attempt to support unified websocket upgrade support.
- For Node.js, with `uprade` hook a Request proxy is created that adds upgrade details (duplex and head data)
- For deno, bun and cloudflare, if the request has `upgrade` header with `websocket` value and `upgrade` hook is defined, it will be called.
The next step is adding a unified `.upgrade(request)` support to srvx adapters, which can be auto-integrated.
(bun requires additional `bun.websocket`, we need to make a srvx plugin anyway to support crossws universally)

feat: support `upgrade` hook (experimental)

---

test/url.test.ts
test/wpt/url_setters_tests.json

Adding Web Platform tests to confirm setter behavior of `FastURL` (thanks for the tip from @anonrig ❤️ )
Currently, 9/298 tests fail on `new URL` with Node 22.15 (12 in 22.14), whichis  set to skip
We probably have some bugs not revealed by these tests, but worth having it I guess.

test: add wpt setter tests for `FastURL`

---

src/_node-compat/request.ts
src/_node-compat/send.ts
src/_plugins.ts
src/adapters/bun.ts
src/adapters/cloudflare.ts
src/adapters/deno.ts
src/adapters/node.ts
src/types.ts

This PR removes the experimental upgrade (#63) introduced in 0.6x
The reason is that true cross-platform websocket support (specially for runtimes like bun that has different top level API) needs [crossws](https://crossws.h3.dev/) the small stubs for upgrade header handling and node wrapper was causing duplicate logic.

refactor!: remove experimental ws upgrade

---

package.json
src/_node-compat/send.ts
src/_utils.node.ts
src/adapters/node.ts

Having top level `node:` imports, can make issues when module graph being resolved even if they are not needed.
Using new [`process.getBuiltinModule`](https://nodejs.org/api/process.html#processgetbuiltinmoduleid) available in recent versions of Deno, Bun, and Node.js v22.3.0+, v20.16.0+, we can lazily and synchronously import Node.js API when needed.

refactor!: use `process.getBuiltinModule` for node

---

src/adapters/_node/request.ts
test/_fixture.ts
test/_tests.ts

resolves #75
When `request.signal` is accessed (to listen or check) we register a lazy abort listener to send Node.js request signal back to web request.

feat(node): call request abort signal

---

docs/1.guide/6.bundler.md

resovles #72 
Improves explanations for using srvx with a bundler.

docs(guide/bundler): improve bundle usage explanation

---

src/adapters/_node/response.ts
test/_fixture.ts
test/_tests.ts

Resolves #78
Also made sure to prioritize `#headersObj` when using `res.clone()` or on internal access of `#response`. We are already on slow paths there, but gets more slow with the extra clone of the headers.

fix(node): only use `req.headers` in `FastResponse` when initialized

---

src/types.ts
test/types.test-d.ts
tsconfig.json
types.d.ts

resolves #82
Example: (`cloudflare.d.ts`)
```ts
declare module "cloudflare:workers" {
export const env: {
TEST: string;
};
}
```
docs for new `cloudflare:workers.env`: https://developers.cloudflare.com/workers/runtime-apis/bindings/#how-to-access-env
(thanks to @danielroe for `IsAny` util ❤️ )

types: allow augmenting `req.runtime.cloudflare.env`

---

src/types.ts

Currently, when using the server with the `manual` option enabled, the server won’t start automatically - you need to call the `serve()` method explicitly.
Even though this method exists in all adapters, it was missing from the  types, which made it invisible and could cause type errors.
This change adds `serve()` to the server interface, so it’s now properly typed and discoverable when working in manual mode.

fix: add missing `Server.serve` type

---

src/adapters/_node/_common.ts
src/adapters/_node/request.ts
src/adapters/_node/response.ts

This PR rewrites FastResponse wrapper:
- simpler and smaller
- Always set status text
- Always set default `content-type` and `content-length` headers
- Inherit full proto keys of current undici Response 
(this adds little perf overhead but probably worth it)

refactor(node): rewrite FastResponse

---

package.json
src/_inherit.ts
src/_url.ts
src/adapters/_node/_common.ts
src/adapters/_node/request.ts
src/adapters/_node/response.ts
test/url.bench.ts

Similar to #109 and #110 this PR rewrites `FastURL` implementation to fully inherit `URL` prototype. 
Also few minor fast paths improved.
Also inherit util improved to partially inherit (so internally we don't need both getter setter)

refactor: reimplement `FastURL`

---

src/adapters/_node/url.ts

Based on #112, we can have internal node `req._url: URL` proxy based on FastURL.
There are few slow paths (like `host`, `hostname`) but it is probably worth it because we have one well tested implementation and later can improve same place.

refactor(node): rewrite `NodeRequestURL` based on `FastURL`

---

src/adapters/_node/request.ts
src/adapters/_node/response.ts

In case that `srvx/node` is accessed outside of node.js compatible runtimes for any reasons, we should avoid global init code depending on Node.js APIs (process.getBuiltinModule)

fix: safer access to `process.getBuiltinModule`

---

src/_url.ts
src/adapters/_node/url.ts

When (internal) `webReq._url.pathname` being updated (h3 uses this for `withBase` util), this PR makes sure node source gets updated.

 fix(node): sync `NodeRequestURL.pathname` changes back to `node req.url`
